<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ConstruSoftTicket.Application\ConstruSoftTicket.Application.csproj" />
    <ProjectReference Include="..\ConstruSoftTicket.Domain\ConstruSoftTicket.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
